# Build Spec for AWS CodeBuild CI

version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y curl gnupg2
#      - pip install pip -U
#      - apt-get -y install nodejs-dev node-gyp libssl1.0-dev
#      - apt-get -y install npm
#      - npm install -g n
#      - npm install -g markdown-link-check

  build:
    commands:
      - ./torchserve_sanity.sh cuda101
      - cd serving-sdk/ && mvn clean install -q && cd ../